# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:launcher/root/zzz/1 with entity @s item.components."minecraft:custom_data".locators.layer0_lock_point
function animated_java:launcher/root/zzz/3 with entity @s item.components."minecraft:custom_data".locators.layer1_lock_point
function animated_java:launcher/root/zzz/5 with entity @s item.components."minecraft:custom_data".locators.layer2_lock_point