# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:forklift/root/zzz/on_tick/select_locator_seat with entity @s data.locators.seat
function animated_java:forklift/root/zzz/on_tick/select_locator_seat_interaction with entity @s data.locators.seat_interaction
function animated_java:forklift/root/zzz/on_tick/select_locator_cake_mount with entity @s data.locators.cake_mount