# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ingredient_vanilla.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ingredient_vanilla', 'function_path': 'animated_java:ingredient_vanilla/remove/this'}
function #animated_java:ingredient_vanilla/as_root/on_remove
execute on passengers run kill @s
kill @s