# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_valve_interaction
function animated_java:mixer/zzz/as_all_locators/execute_as_uuid with storage aj:temp args