# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.layer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'layer', 'function_path': 'animated_java:layer/variants/default/apply'}
execute on passengers if entity @s[tag=aj.layer.bone.layer] run function animated_java:layer/variants/default/zzz/apply_to_bone_layer
execute on passengers if entity @s[tag=aj.layer.bone.frosting] run function animated_java:layer/variants/default/zzz/apply_to_bone_frosting
return 1