# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(text_display_milk_check) {transformation: [0f,0f,0f,-4.0625f,0f,0f,0f,10f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_milk) {transformation: [-1f,0f,0f,-4f,0f,1f,0f,10.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_flour_check) {transformation: [0f,0f,0f,-2.0625f,0f,0f,0f,10f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flour2) {transformation: [0.7071f,0.0616f,0.7044f,-2f,0.2706f,0.8968f,-0.3501f,10.5f,-0.0163f,0.011f,0.0154f,0.016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flour_item) {transformation: [0.7071f,0f,0.7071f,-2f,0.2706f,0.9239f,-0.2706f,10.5f,-0.0163f,0.0096f,0.0163f,0.016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flour) {transformation: [-1f,0f,0f,-2f,0f,1f,0f,10.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_sugar_check) {transformation: [0f,0f,0f,-0.0625f,0f,0f,0f,10f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sugar_item) {transformation: [-0.7071f,0f,-0.7071f,0f,-0.2706f,0.9239f,0.2706f,10.5f,0.0163f,0.0096f,-0.0163f,0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sugar) {transformation: [-1f,0f,0f,0f,0f,1f,0f,10.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_egg_check) {transformation: [0f,0f,0f,1.9375f,0f,0f,0f,10f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_eggs) {transformation: [-1f,0f,0f,2f,0f,1f,0f,10.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_flavor_check) {transformation: [0f,0f,0f,3.9375f,0f,0f,0f,10f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flavor) {transformation: [-1f,0f,0f,4f,0f,1f,0f,10.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}