# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.eyes] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_eyes set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.nose] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_nose set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.hair_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_hair_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.hair_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_hair_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.hand_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_hand_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.arm_left_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_arm_left_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.arm_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_arm_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.leg_left_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_leg_left_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.leg_right_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_leg_right_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.hand_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_hand_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.arm_right_down] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_arm_right_down set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.arm_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_arm_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.pants] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_pants set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.left_breast] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_left_breast set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.right_breast] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_right_breast set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.troll.node.waist] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_waist set from storage aj:uuid main.out