# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ingredient_chocolate.root] run return 0
execute if entity @s[tag=aj.ingredient_chocolate.animation.spawn.playing] run function animated_java:ingredient_chocolate/animations/spawn/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~