# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_flow) {transformation: [-2.6667f,0f,0f,0f,0f,0f,0f,-2.9375f,0f,0f,-2.6667f,9f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_valve) {transformation: [-4.125f,0f,0f,0f,0f,4.125f,0f,4f,0f,0f,-4.125f,9f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:mixer/animations/pour/zzz/frames/60_root_commands