# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.forklift.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'forklift', 'function_path': 'animated_java:forklift/animations/steer_reset/play'}
tag @s add aj.forklift.animation.steer_reset.playing
scoreboard players set @s aj.steer_reset.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:forklift/animations/steer_reset/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only