# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/at_all_locators'}
data remove storage aj:temp args
$data modify storage aj:temp args.command set value '$(command)'
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:mixer/zzz/at_all_locators/as_data