# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.mix.frame dummy
scoreboard objectives add aj.pour.frame dummy
scoreboard objectives add aj.open_lid.frame dummy
scoreboard objectives add aj.close_lid.frame dummy