# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.pos.frame
scoreboard objectives remove aj.mix.frame
scoreboard objectives remove aj.pour.frame
scoreboard objectives remove aj.open_lid.frame
scoreboard objectives remove aj.close_lid.frame
scoreboard objectives remove aj.filled0.frame
scoreboard objectives remove aj.filled1.frame
scoreboard objectives remove aj.filled2.frame
scoreboard objectives remove aj.filled3.frame
scoreboard objectives remove aj.filled4.frame
scoreboard objectives remove aj.filled5.frame
scoreboard objectives remove aj.show_badges.frame
scoreboard objectives remove aj.hide_badges.frame
scoreboard objectives remove aj.milk_check.frame
scoreboard objectives remove aj.flour_check.frame
scoreboard objectives remove aj.sugar_check.frame
scoreboard objectives remove aj.eggs_check.frame
scoreboard objectives remove aj.flavor_check.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"mixer",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]