# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/set_default_pose'}
execute on passengers if entity @s[tag=aj.mixer.bone.batter] run data merge entity @s {transformation: [-8f,0f,0f,0f,0f,8f,0f,0.0625f,0f,0f,-8f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.handle] run data merge entity @s {transformation: [-4.6667f,0f,0f,0f,0f,4.6667f,0f,8f,0f,0f,-4.6667f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.lid] run data merge entity @s {transformation: [-8f,0f,0f,0f,0f,8f,0f,7f,0f,0f,-8f,-6f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.spout] run data merge entity @s {transformation: [-6.6667f,0f,0f,0f,0f,6.6667f,0f,0f,0f,0f,-6.6667f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.flow] run data merge entity @s {transformation: [-2.6667f,0f,0f,0f,0f,2.6667f,0f,1.0625f,0f,0f,-2.6667f,9f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.valve] run data merge entity @s {transformation: [-3.6667f,0f,0f,0f,0f,3.6667f,0f,4f,0f,0f,-3.6667f,9f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.batter_output_plaque] run data merge entity @s {transformation: [-2f,0f,0f,-3.5f,0f,2f,0f,2.5f,0f,0f,-2f,6.0625f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.basin] run data merge entity @s {transformation: [-8f,0f,0f,0f,0f,8f,0f,0f,0f,0f,-8f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.milk] run data merge entity @s {transformation: [-1f,0f,0f,-3f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.flour] run data merge entity @s {transformation: [-1f,0f,0f,-1.5f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.sugar] run data merge entity @s {transformation: [-1f,0f,0f,0f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.eggs] run data merge entity @s {transformation: [-1f,0f,0f,1.5f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}
execute on passengers if entity @s[tag=aj.mixer.bone.flavor] run data merge entity @s {transformation: [-1f,0f,0f,3f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1}