# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.forklift.root] run return 0
execute if entity @s[tag=aj.forklift.animation.fork_height_0.playing] run function animated_java:forklift/animations/fork_height_0/zzz/on_tick
execute if entity @s[tag=aj.forklift.animation.fork_height_1.playing] run function animated_java:forklift/animations/fork_height_1/zzz/on_tick
execute if entity @s[tag=aj.forklift.animation.fork_height_2.playing] run function animated_java:forklift/animations/fork_height_2/zzz/on_tick
execute if entity @s[tag=aj.forklift.animation.fork_height_3.playing] run function animated_java:forklift/animations/fork_height_3/zzz/on_tick
execute on passengers if entity @s[tag=aj.forklift.data] run function animated_java:forklift/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~