# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.forklift.root] run return 0
function #animated_java:forklift/as_root/pre_tick
execute if entity @s[tag=aj.forklift.animation.idle.playing] run function animated_java:forklift/animations/idle/zzz/on_tick
execute on passengers if entity @s[tag=aj.forklift.data] run function animated_java:forklift/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~
function #animated_java:forklift/as_root/post_tick