# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_berries.node.berries] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_berries set from storage aj:uuid main.out