# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.static_pipette.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'static_pipette', 'function_path': 'animated_java:static_pipette/animations/squish/next_frame'}
execute if score @s aj.squish.frame matches 6.. run scoreboard players set @s aj.squish.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.squish.frame
execute at @s run function animated_java:static_pipette/animations/squish/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.squish.frame 1