# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.static_pipette.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'static_pipette', 'function_path': 'animated_java:static_pipette/animations/squish/set_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.squish.frame $(frame)
execute at @s run function animated_java:static_pipette/animations/squish/zzz/set_frame with storage aj:temp