# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".uuids.locator_seat
function animated_java:forklift/zzz/as_own_locator_entities/execute_as_uuid with storage aj:temp
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".uuids.locator_seat_interaction
function animated_java:forklift/zzz/as_own_locator_entities/execute_as_uuid with storage aj:temp
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".uuids.locator_cake_mount
function animated_java:forklift/zzz/as_own_locator_entities/execute_as_uuid with storage aj:temp