# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".uuids.locator_milk_lock_point
function animated_java:frosting_mixer/zzz/as_own_locator_entities/execute_as_uuid with storage aj:temp