# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:pan/animations/fill_batter/zzz/frames/$(frame) with entity @s item.components."minecraft:custom_data".uuids
execute on passengers run data modify entity @s[tag=aj.global.data] start_interpolation set value -1
return 1