# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.data_data set from storage aj:uuid main.out
summon minecraft:item_display ^0 ^1 ^0 {Tags:["aj.forklift.bone.body.child","aj.forklift.bone.body.child.locator","aj.forklift.bone.body.decendant","aj.forklift.bone.body.decendant.locator","aj.forklift.bone.body.tree","aj.forklift.entity","aj.forklift.locator","aj.forklift.locator.seat","aj.forklift.node","aj.forklift.node.seat","aj.global.bone.body.child","aj.global.bone.body.child.locator","aj.global.bone.body.decendant","aj.global.bone.body.decendant.locator","aj.global.bone.body.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.seat","aj.new"]}
execute as @n[ type=minecraft:item_display, tag=aj.new,tag=aj.global.locator ] run function animated_java:forklift/zzz/summon/as_data_entity/as_locator/seat
data modify entity @s item.components."minecraft:custom_data".locators.seat.uuid set from storage aj:uuid main.out
summon minecraft:interaction ^0 ^0 ^0 {Tags:["aj.forklift.bone.body.child","aj.forklift.bone.body.child.locator","aj.forklift.bone.body.decendant","aj.forklift.bone.body.decendant.locator","aj.forklift.bone.body.tree","aj.forklift.entity","aj.forklift.locator","aj.forklift.locator.seat_interaction","aj.forklift.node","aj.forklift.node.seat_interaction","aj.global.bone.body.child","aj.global.bone.body.child.locator","aj.global.bone.body.decendant","aj.global.bone.body.decendant.locator","aj.global.bone.body.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.seat_interaction","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new,tag=aj.global.locator ] run function animated_java:forklift/zzz/summon/as_data_entity/as_locator/seat_interaction
data modify entity @s item.components."minecraft:custom_data".locators.seat_interaction.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.forklift.node.front_right_wheel] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_front_right_wheel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.forklift.node.back_right_wheel] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_back_right_wheel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.forklift.node.front_left_wheel] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_front_left_wheel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.forklift.node.back_left_wheel] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_back_left_wheel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.forklift.node.forks] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_forks set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.forklift.node.crane] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_crane set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.forklift.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_body set from storage aj:uuid main.out