# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.layer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'layer', 'function_path': 'animated_java:layer/animations/monch/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.monch.frame $(frame)
execute at @s run function animated_java:layer/animations/monch/zzz/apply_frame with storage aj:temp