# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.frosting_mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'frosting_mixer', 'function_path': 'animated_java:frosting_mixer/animations/show_ingredient_badges/stop'}
tag @s remove aj.frosting_mixer.animation.show_ingredient_badges.playing
scoreboard players set @s aj.show_ingredient_badges.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:frosting_mixer/animations/show_ingredient_badges/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only