# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:frosting_mixer/zzz/summon/as_data_entity
execute if data storage aj:temp args.variant run function animated_java:frosting_mixer/zzz/summon/variant_arg/process with storage aj:temp args
function animated_java:frosting_mixer/set_default_pose
execute if data storage aj:temp args.animation run function animated_java:frosting_mixer/zzz/summon/animation_arg/process with storage aj:temp args
tp @s ~ ~ ~ ~ ~
execute at @s on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s add frosting_mixer
scoreboard players set @s frosting_mixer_state 0
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
function #animated_java:frosting_mixer/as_root/on_summon