const { readdirSync, readFileSync } = require('fs')
const { join, basename } = require('path')

function getVectorScoreNames(name, objective) {
	let xName = name
	let zName = name
	let xObjective = objective
	let zObjective = objective
	if (name.startsWith('@')) {
		xObjective = objective + '.x'
		zObjective = objective + '.z'
	} else {
		xName = name + '.x'
		zName = name + '.z'
	}
	return { xName, zName, xObjective, zObjective }
}

const musicLengths = new Map()

function readJsonData() {
	const data = {}
	for (const path of readdirSync('./driven')) {
		if (path.endsWith('.json')) {
			const name = basename(path, '.json')
			data[name] = JSON.parse(readFileSync(join('./driven', path), 'utf-8'))
		}
	}
	return data
}

module.exports = {
	libDir: null, // default: "null", determine where mcb looks for libraries, default is the bundled install location
	generatedDirName: 'zzz', // default: "zzz", the name of the directory where mcb will put generated files
	internalScoreboardName: 'mcb.i', // default: "mcb.internal", the name of the internal scoreboard
	header: null, // default: "#This file was generated by mcb\n", the header to put at the top of supported generated files
	ioThreadCount: 1, // default: 1, the number of threads to use for IO operations, 1 is syncronous.
	getVectorScoreNames,
	musicLengths,
	dev: false,
	setup(mcb) {
		mcb.events.onPreBuild.subscribe(async () => {
			musicLengths.set('boss', 500)
			musicLengths.set('gameplay', 500)
			musicLengths.set('tutorial', 500)

			this.driven = readJsonData()

			this.dev = process.argv.includes('--dev')
		})
	},
}
