# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.splat.root] run return 0
function #animated_java:splat/as_root/pre_tick
execute if entity @s[tag=aj.splat.animation.splat.playing] run function animated_java:splat/animations/splat/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:splat/as_root/post_tick