# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.static_pipette.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'static_pipette', 'function_path': 'animated_java:static_pipette/animations/unsquish/stop'}
tag @s remove aj.static_pipette.animation.unsquish.playing
scoreboard players set @s aj.unsquish.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:static_pipette/animations/unsquish/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only