# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_handle) {transformation: [-5.5417f,0f,0f,0f,0f,5.5417f,0f,8f,0f,0f,-5.5417f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid) {transformation: [-8f,0f,0f,0f,0f,8f,0f,7f,0f,0f,-8f,-6f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s item.components."minecraft:custom_data" merge value {"cameras":{},"locators":{"handle_zone":{"posx":4.286263797015736e-16,"posy":8,"posz":-3.5,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:mixer/animations/close_lid/zzz/frames/40_root_commands