# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.data_data set from storage aj:uuid main.out
summon minecraft:item_display ^0 ^4 ^0 {Tags:["aj.global.bone.oven.child","aj.global.bone.oven.child.locator","aj.global.bone.oven.decendant","aj.global.bone.oven.decendant.locator","aj.global.bone.oven.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.cake_lock_point","aj.new","aj.oven.bone.oven.child","aj.oven.bone.oven.child.locator","aj.oven.bone.oven.decendant","aj.oven.bone.oven.decendant.locator","aj.oven.bone.oven.tree","aj.oven.entity","aj.oven.locator","aj.oven.locator.cake_lock_point","aj.oven.node","aj.oven.node.cake_lock_point"]}
execute as @n[ type=minecraft:item_display, tag=aj.new, tag=aj.oven.locator.cake_lock_point, distance=..5 ] run function animated_java:oven/zzz/2
data modify entity @s item.components."minecraft:custom_data".locators.cake_lock_point.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.oven.node.oven] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_oven set from storage aj:uuid main.out