# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.static_pipette.root] run return 0
function #animated_java:static_pipette/as_root/pre_tick
execute if entity @s[tag=aj.static_pipette.animation.squish.playing] run function animated_java:static_pipette/animations/squish/zzz/on_tick
execute if entity @s[tag=aj.static_pipette.animation.unsquish.playing] run function animated_java:static_pipette/animations/unsquish/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:static_pipette/as_root/post_tick