# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s frosting_mixer_state 1
function animated_java:frosting_mixer/animations/show_ingredient_badges/play