# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_contents) {transformation: [-3.3333f,0f,0f,0f,0f,3.3333f,0f,8.9375f,0f,0f,-3.3667f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frosting_nozzle) {transformation: [-2.6667f,0f,0f,0f,0f,2.6667f,0f,8f,0f,0f,-2.6933f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid) {transformation: [-4.6667f,0f,0f,0f,0f,4.6667f,0f,13.5f,0f,0f,-4.7133f,-3.0925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_basin) {transformation: [-4.6667f,0f,0f,0f,0f,4.6667f,0f,11f,0f,0f,-4.7133f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s item.components."minecraft:custom_data" merge value {"cameras":{},"locators":{"milk_lock_point":{"posx":-2.999999999999999,"posy":1,"posz":-6,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:frosting_mixer/animations/mix/zzz/frames/40_root_commands