# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.launcher.root] run return 0
function #animated_java:launcher/as_root/pre_tick
execute on passengers if entity @s[tag=aj.launcher.data] run function animated_java:launcher/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function #animated_java:launcher/as_root/post_tick