# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.static_pipette.node.6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_6 set from storage aj:uuid main.out