# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_seat
function animated_java:forklift/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_seat_interaction
function animated_java:forklift/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_cake_mount
function animated_java:forklift/zzz/as_all_locators/execute_as_uuid with storage aj:temp args