# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.launcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'launcher', 'function_path': 'animated_java:launcher/animations/launch/play'}
tag @s add aj.launcher.animation.launch.playing
scoreboard players set @s aj.launch.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:launcher/animations/launch/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only