# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute if score @s aj.spin.frame matches -1 run function animated_java:fan/animations/spin/zzz/commands_keyframe_loop_patch
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.spin.frame
function animated_java:fan/animations/spin/zzz/apply_frame with storage aj:temp
execute if score @s aj.spin.frame matches 19.. run return run scoreboard players set @s aj.spin.frame -1
scoreboard players add @s aj.spin.frame 1