# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.pan.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pan', 'function_path': 'animated_java:pan/animations/pause_all'}
tag @s remove aj.pan.animation.empty.playing
tag @s remove aj.pan.animation.fill_batter.playing
tag @s remove aj.pan.animation.finish_baking.playing