# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.pan.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pan', 'function_path': 'animated_java:pan/animations/finish_baking/next_frame'}
execute if score @s aj.finish_baking.frame matches 21.. run scoreboard players set @s aj.finish_baking.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.finish_baking.frame
execute at @s run function animated_java:pan/animations/finish_baking/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.finish_baking.frame 1