# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leaves) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.125f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leaves2) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.125f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_carrot) {transformation: [0f,0f,0f,0f,0f,0f,0f,4.125f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}