# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_handle) {transformation: [-4.6667f,0f,0f,0f,0f,4.6667f,0f,8f,0f,0f,-4.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid) {transformation: [-8f,0f,0f,0f,0f,8f,0f,7f,0f,0f,-8f,-6f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flow) {transformation: [-2.6667f,0f,0f,0f,0f,0f,0f,1.0625f,0f,0f,-2.6667f,9f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_batter_output_plaque) {transformation: [-2f,0f,0f,-3.5f,0f,2f,0f,2.5f,0f,0f,-2f,6.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_milk) {transformation: [-1f,0f,0f,-3f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flour) {transformation: [-1f,0f,0f,-1.5f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sugar) {transformation: [-1f,0f,0f,0f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_eggs) {transformation: [-1f,0f,0f,1.5f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flavor) {transformation: [-1f,0f,0f,3f,0f,1f,0f,11.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s item.components."minecraft:custom_data" merge value {"cameras":{},"locators":{"handle_zone":{"posx":4.286263797015736e-16,"posy":8,"posz":-3.5,"roty":0,"rotx":0},"spout_output":{"posx":-1.102182119232618e-15,"posy":-3,"posz":9,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:mixer/animations/open_lid/zzz/frames/0_root_commands