# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_handle) {transformation: [-5.5417f,0f,0f,0f,0f,0f,-5.5417f,13f,0f,-5.5417f,0f,-7f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lid) {transformation: [-8f,0f,0f,0f,0f,0f,-8f,7f,0f,-8f,0f,-6f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:mixer/animations/open_lid/zzz/frames/40_root_commands