# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.orders.root] run return 0
function #animated_java:orders/as_root/pre_tick
execute if entity @s[tag=aj.orders.animation.pos.playing] run function animated_java:orders/animations/pos/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:orders/as_root/post_tick