# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.frosting_mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'frosting_mixer', 'function_path': 'animated_java:frosting_mixer/as_own_locator_entities'}
$data modify storage aj:temp command set value '$(command)'
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:frosting_mixer/zzz/as_own_locator_entities/as_data