# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/variants/hide_badges/apply'}
execute on passengers if entity @s[tag=aj.mixer.bone.batter] run function animated_java:mixer/variants/hide_badges/zzz/apply_to_bone_batter
execute on passengers if entity @s[tag=aj.mixer.bone.milk] run function animated_java:mixer/variants/hide_badges/zzz/apply_to_bone_milk
execute on passengers if entity @s[tag=aj.mixer.bone.flour] run function animated_java:mixer/variants/hide_badges/zzz/apply_to_bone_flour
execute on passengers if entity @s[tag=aj.mixer.bone.sugar] run function animated_java:mixer/variants/hide_badges/zzz/apply_to_bone_sugar
execute on passengers if entity @s[tag=aj.mixer.bone.eggs] run function animated_java:mixer/variants/hide_badges/zzz/apply_to_bone_eggs
execute on passengers if entity @s[tag=aj.mixer.bone.flavor] run function animated_java:mixer/variants/hide_badges/zzz/apply_to_bone_flavor
return 1