# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
tp @s ^0 ^9 ^9 ~0 ~0
scoreboard players operation @s aj.id = aj.last_id aj.id
tag @s add mixer_valve
data merge entity @s {response:true,width:3,height:1}