# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.pan.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pan', 'function_path': 'animated_java:pan/animations/fill_batter/next_frame'}
execute if score @s aj.fill_batter.frame matches 31.. run scoreboard players set @s aj.fill_batter.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.fill_batter.frame
execute at @s run function animated_java:pan/animations/fill_batter/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.fill_batter.frame 1