# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mixer/root/zzz/on_tick/select_locator_handle_zone with entity @s item.components."minecraft:custom_data".locators.handle_zone
function animated_java:mixer/root/zzz/on_tick/select_locator_valve_interaction with entity @s item.components."minecraft:custom_data".locators.valve_interaction
function animated_java:mixer/root/zzz/on_tick/select_locator_spout_output with entity @s item.components."minecraft:custom_data".locators.spout_output