# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ingredient_milk.root] run return 0
function #animated_java:ingredient_milk/as_root/pre_tick
execute if entity @s[tag=aj.ingredient_milk.animation.spawn.playing] run function animated_java:ingredient_milk/animations/spawn/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:ingredient_milk/as_root/post_tick