# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.static_pipette.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'static_pipette', 'function_path': 'animated_java:static_pipette/variants/chocolate/apply'}
execute on passengers if entity @s[tag=aj.static_pipette.bone.7] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_7
execute on passengers if entity @s[tag=aj.static_pipette.bone.8] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_8
execute on passengers if entity @s[tag=aj.static_pipette.bone.9] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_9
execute on passengers if entity @s[tag=aj.static_pipette.bone.10] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_10
execute on passengers if entity @s[tag=aj.static_pipette.bone.1] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_1
execute on passengers if entity @s[tag=aj.static_pipette.bone.2] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_2
execute on passengers if entity @s[tag=aj.static_pipette.bone.3] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_3
execute on passengers if entity @s[tag=aj.static_pipette.bone.4] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_4
execute on passengers if entity @s[tag=aj.static_pipette.bone.5] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_5
execute on passengers if entity @s[tag=aj.static_pipette.bone.6] run function animated_java:static_pipette/variants/chocolate/zzz/apply_to_bone_6
return 1