# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tip) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,3.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bag) {transformation: [-4.1771f,0f,0f,0f,0f,2.5062f,0f,0f,0f,0f,-4.1771f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:static_pipette/animations/squish/zzz/frames/5_root_commands