# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/variants/default/apply'}
execute on passengers if entity @s[tag=aj.mixer.bone.batter] run function animated_java:mixer/variants/default/zzz/apply_to_bone_batter
execute on passengers if entity @s[tag=aj.mixer.bone.handle] run function animated_java:mixer/variants/default/zzz/apply_to_bone_handle
execute on passengers if entity @s[tag=aj.mixer.bone.lid] run function animated_java:mixer/variants/default/zzz/apply_to_bone_lid
execute on passengers if entity @s[tag=aj.mixer.bone.spout] run function animated_java:mixer/variants/default/zzz/apply_to_bone_spout
execute on passengers if entity @s[tag=aj.mixer.bone.flow] run function animated_java:mixer/variants/default/zzz/apply_to_bone_flow
execute on passengers if entity @s[tag=aj.mixer.bone.valve] run function animated_java:mixer/variants/default/zzz/apply_to_bone_valve
execute on passengers if entity @s[tag=aj.mixer.bone.basin] run function animated_java:mixer/variants/default/zzz/apply_to_bone_basin
execute on passengers if entity @s[tag=aj.mixer.bone.malk] run function animated_java:mixer/variants/default/zzz/apply_to_bone_malk
execute on passengers if entity @s[tag=aj.mixer.bone.milk] run function animated_java:mixer/variants/default/zzz/apply_to_bone_milk
execute on passengers if entity @s[tag=aj.mixer.bone.flour2] run function animated_java:mixer/variants/default/zzz/apply_to_bone_flour2
execute on passengers if entity @s[tag=aj.mixer.bone.flour_item] run function animated_java:mixer/variants/default/zzz/apply_to_bone_flour_item
execute on passengers if entity @s[tag=aj.mixer.bone.flour] run function animated_java:mixer/variants/default/zzz/apply_to_bone_flour
execute on passengers if entity @s[tag=aj.mixer.bone.sugar_item] run function animated_java:mixer/variants/default/zzz/apply_to_bone_sugar_item
execute on passengers if entity @s[tag=aj.mixer.bone.sugar] run function animated_java:mixer/variants/default/zzz/apply_to_bone_sugar
execute on passengers if entity @s[tag=aj.mixer.bone.eggs_item] run function animated_java:mixer/variants/default/zzz/apply_to_bone_eggs_item
execute on passengers if entity @s[tag=aj.mixer.bone.eggs] run function animated_java:mixer/variants/default/zzz/apply_to_bone_eggs
execute on passengers if entity @s[tag=aj.mixer.bone.berries] run function animated_java:mixer/variants/default/zzz/apply_to_bone_berries
execute on passengers if entity @s[tag=aj.mixer.bone.vanilla] run function animated_java:mixer/variants/default/zzz/apply_to_bone_vanilla
execute on passengers if entity @s[tag=aj.mixer.bone.chocolate] run function animated_java:mixer/variants/default/zzz/apply_to_bone_chocolate
execute on passengers if entity @s[tag=aj.mixer.bone.flavor] run function animated_java:mixer/variants/default/zzz/apply_to_bone_flavor
return 1