# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/variants/default/apply'}
execute on passengers if entity @s[tag=aj.mixer.bone.batter] run function animated_java:mixer/variants/default/zzz/apply_to_bone_batter
execute on passengers if entity @s[tag=aj.mixer.bone.handle] run function animated_java:mixer/variants/default/zzz/apply_to_bone_handle
execute on passengers if entity @s[tag=aj.mixer.bone.lid] run function animated_java:mixer/variants/default/zzz/apply_to_bone_lid
execute on passengers if entity @s[tag=aj.mixer.bone.spout] run function animated_java:mixer/variants/default/zzz/apply_to_bone_spout
execute on passengers if entity @s[tag=aj.mixer.bone.flow] run function animated_java:mixer/variants/default/zzz/apply_to_bone_flow
execute on passengers if entity @s[tag=aj.mixer.bone.valve] run function animated_java:mixer/variants/default/zzz/apply_to_bone_valve
execute on passengers if entity @s[tag=aj.mixer.bone.basin] run function animated_java:mixer/variants/default/zzz/apply_to_bone_basin
return 1