# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_milk.node.malk] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_malk set from storage aj:uuid main.out