# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.splat.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'splat', 'function_path': 'animated_java:splat/animations/splat/next_frame'}
execute if score @s aj.splat.frame matches 106.. run scoreboard players set @s aj.splat.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.splat.frame
execute at @s run function animated_java:splat/animations/splat/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.splat.frame 1