# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args merge from entity @s data.locators.seat
function animated_java:forklift/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.seat_interaction
function animated_java:forklift/zzz/at_all_locators/execute_at_transform with storage aj:temp args
data modify storage aj:temp args merge from entity @s data.locators.cake_mount
function animated_java:forklift/zzz/at_all_locators/execute_at_transform with storage aj:temp args