# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.frosting_mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'frosting_mixer', 'function_path': 'animated_java:frosting_mixer/variants/contents_chocolate/apply'}
execute on passengers if entity @s[tag=aj.frosting_mixer.bone.contents] run function animated_java:frosting_mixer/variants/contents_chocolate/zzz/apply_to_bone_contents
execute on passengers if entity @s[tag=aj.frosting_mixer.bone.basin] run function animated_java:frosting_mixer/variants/contents_chocolate/zzz/apply_to_bone_basin
return 1