# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.pan] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pan set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.layer_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_layer_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.layer_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_layer_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.layer_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_layer_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.layer_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_layer_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.frosting_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frosting_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.frosting_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frosting_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.frosting_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frosting_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.pan.node.frosting_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frosting_4 set from storage aj:uuid main.out