# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:forklift/remove/zzz/this/kill_locator with entity @s item.components."minecraft:custom_data".locators.seat
function animated_java:forklift/remove/zzz/this/kill_locator with entity @s item.components."minecraft:custom_data".locators.seat_interaction
function animated_java:forklift/remove/zzz/this/kill_locator with entity @s item.components."minecraft:custom_data".locators.cake_mount