# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args merge from entity @s data.locators.valve_interaction
function animated_java:mixer/zzz/at_all_locators/execute_at_transform with storage aj:temp args