# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pan.root] run return 0
execute if entity @s[tag=aj.pan.animation.empty.playing] run function animated_java:pan/animations/empty/zzz/on_tick
execute if entity @s[tag=aj.pan.animation.fill_batter.playing] run function animated_java:pan/animations/fill_batter/zzz/on_tick
execute if entity @s[tag=aj.pan.animation.finish_baking.playing] run function animated_java:pan/animations/finish_baking/zzz/on_tick
execute if entity @s[tag=aj.pan.animation.frost1.playing] run function animated_java:pan/animations/frost1/zzz/on_tick
execute if entity @s[tag=aj.pan.animation.frost2.playing] run function animated_java:pan/animations/frost2/zzz/on_tick
execute if entity @s[tag=aj.pan.animation.frost3.playing] run function animated_java:pan/animations/frost3/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~