# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pan.root] run return 0
function #animated_java:pan/as_root/pre_tick
execute if entity @s[tag=aj.pan.animation.fill_batter.playing] run function animated_java:pan/animations/fill_batter/zzz/on_tick
execute if entity @s[tag=aj.pan.animation.empty.playing] run function animated_java:pan/animations/empty/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:pan/as_root/post_tick