# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.data_data set from storage aj:uuid main.out
summon minecraft:interaction ^0 ^11 ^9 {Tags:["aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.valve_interaction","aj.global.root.child","aj.global.root.child.locator","aj.mixer.entity","aj.mixer.locator","aj.mixer.locator.valve_interaction","aj.mixer.node","aj.mixer.node.valve_interaction","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new,tag=aj.global.locator ] run function animated_java:mixer/zzz/summon/as_data_entity/as_locator/valve_interaction
data modify entity @s item.components."minecraft:custom_data".locators.valve_interaction.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.batter] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_batter set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.handle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_handle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.lid] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_lid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.spout] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_spout set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flow] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_flow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.valve] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_valve set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.basin] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_basin set from storage aj:uuid main.out