# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.data_data set from storage aj:uuid main.out
summon minecraft:interaction ^0 ^9 ^9 {Tags:["aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.valve_interaction","aj.global.root.child","aj.global.root.child.locator","aj.mixer.entity","aj.mixer.locator","aj.mixer.locator.valve_interaction","aj.mixer.node","aj.mixer.node.valve_interaction","aj.new"]}
execute as @n[ type=minecraft:interaction, tag=aj.new, tag=aj.mixer.locator.valve_interaction, distance=..13.727922061357855 ] run function animated_java:mixer/zzz/summon/as_data_entity/as_locator/valve_interaction
data modify entity @s item.components."minecraft:custom_data".uuids.locator_valve_interaction set from storage aj:uuid main.out
data modify entity @s item.components."minecraft:custom_data".locators.valve_interaction.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.batter] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_batter set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.handle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_handle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.lid] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_lid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.spout] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_spout set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flow] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_flow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.valve] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_valve set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.basin] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_basin set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.milk_check] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.text_display_milk_check set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.milk] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_milk set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flour_check] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.text_display_flour_check set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flour2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_flour2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flour_item] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_flour_item set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flour] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_flour set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.sugar_check] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.text_display_sugar_check set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.sugar_item] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_sugar_item set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.sugar] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_sugar set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.egg_check] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.text_display_egg_check set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.eggs] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_eggs set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flavor_check] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.text_display_flavor_check set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mixer.node.flavor] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_flavor set from storage aj:uuid main.out