# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(text_display_sugar_check) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sugar_item) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sugar) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_flavor_check) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_berries) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_vanilla) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chocolate) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flavor) {transformation: [0f,0f,0f,-0.5f,0f,0f,0f,15f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}