# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.data_data set from storage aj:uuid main.out
summon minecraft:item_display ^0 ^1.0625 ^0 {Tags:["aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.layer0_lock_point","aj.global.root.child","aj.global.root.child.locator","aj.launcher.entity","aj.launcher.locator","aj.launcher.locator.layer0_lock_point","aj.launcher.node","aj.launcher.node.layer0_lock_point","aj.new"]}
execute as @n[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator] run function animated_java:launcher/zzz/2
data modify entity @s item.components."minecraft:custom_data".locators.layer0_lock_point.uuid set from storage aj:uuid main.out
summon minecraft:item_display ^0 ^2.0625 ^0 {Tags:["aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.layer1_lock_point","aj.global.root.child","aj.global.root.child.locator","aj.launcher.entity","aj.launcher.locator","aj.launcher.locator.layer1_lock_point","aj.launcher.node","aj.launcher.node.layer1_lock_point","aj.new"]}
execute as @n[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator] run function animated_java:launcher/zzz/3
data modify entity @s item.components."minecraft:custom_data".locators.layer1_lock_point.uuid set from storage aj:uuid main.out
summon minecraft:item_display ^0 ^3.0625 ^0 {Tags:["aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.layer2_lock_point","aj.global.root.child","aj.global.root.child.locator","aj.launcher.entity","aj.launcher.locator","aj.launcher.locator.layer2_lock_point","aj.launcher.node","aj.launcher.node.layer2_lock_point","aj.new"]}
execute as @n[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator] run function animated_java:launcher/zzz/4
data modify entity @s item.components."minecraft:custom_data".locators.layer2_lock_point.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.launcher.node.pan] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_pan set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.launcher.node.spring] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item.components."minecraft:custom_data".bones.bone_spring set from storage aj:uuid main.out