# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
tp @s ^0 ^1.0625 ^0 ~0 ~0
tag @s add pan_lock_point