# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".locators.cake_lock_point.uuid
function animated_java:launcher/zzz/execute with storage aj:temp