# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".locators.layer0_lock_point.uuid
function animated_java:launcher/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".locators.layer1_lock_point.uuid
function animated_java:launcher/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s item.components."minecraft:custom_data".locators.layer2_lock_point.uuid
function animated_java:launcher/zzz/execute with storage aj:temp