# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_milk_badge) {transformation: [-4f,0f,0f,-6f,0f,4f,0f,8f,0f,0f,-4f,-6f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sugar_item) {transformation: [-0.7071f,0f,-0.7071f,-1f,-0.2706f,0.9239f,0.2706f,15.5f,0.0163f,0.0096f,-0.0163f,0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sugar) {transformation: [-1f,0f,0f,-1f,0f,1f,0f,15.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_flavor) {transformation: [-1f,0f,0f,1f,0f,1f,0f,15.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}