# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mixer.root] run return 0
execute if entity @s[tag=aj.mixer.animation.pos.playing] run function animated_java:mixer/animations/pos/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.mix.playing] run function animated_java:mixer/animations/mix/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.pour.playing] run function animated_java:mixer/animations/pour/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.open_lid.playing] run function animated_java:mixer/animations/open_lid/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.close_lid.playing] run function animated_java:mixer/animations/close_lid/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.filled0.playing] run function animated_java:mixer/animations/filled0/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.filled1.playing] run function animated_java:mixer/animations/filled1/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.filled2.playing] run function animated_java:mixer/animations/filled2/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.filled3.playing] run function animated_java:mixer/animations/filled3/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.filled4.playing] run function animated_java:mixer/animations/filled4/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.filled5.playing] run function animated_java:mixer/animations/filled5/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.show_badges.playing] run function animated_java:mixer/animations/show_badges/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.hide_badges.playing] run function animated_java:mixer/animations/hide_badges/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.milk_check.playing] run function animated_java:mixer/animations/milk_check/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.flour_check.playing] run function animated_java:mixer/animations/flour_check/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.sugar_check.playing] run function animated_java:mixer/animations/sugar_check/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.eggs_check.playing] run function animated_java:mixer/animations/eggs_check/zzz/on_tick
execute if entity @s[tag=aj.mixer.animation.flavor_check.playing] run function animated_java:mixer/animations/flavor_check/zzz/on_tick
execute on passengers if entity @s[tag=aj.mixer.data] run function animated_java:mixer/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~