# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.pan.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pan', 'function_path': 'animated_java:pan/variants/batter_carrot/apply'}
execute on passengers if entity @s[tag=aj.pan.bone.layer_1] run function animated_java:pan/variants/batter_carrot/zzz/apply_to_bone_layer_1
execute on passengers if entity @s[tag=aj.pan.bone.layer_2] run function animated_java:pan/variants/batter_carrot/zzz/apply_to_bone_layer_2
execute on passengers if entity @s[tag=aj.pan.bone.layer_3] run function animated_java:pan/variants/batter_carrot/zzz/apply_to_bone_layer_3
execute on passengers if entity @s[tag=aj.pan.bone.layer_4] run function animated_java:pan/variants/batter_carrot/zzz/apply_to_bone_layer_4
return 1