# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/animations/pause_all'}
tag @s remove aj.mixer.animation.mix.playing
tag @s remove aj.mixer.animation.pour.playing
tag @s remove aj.mixer.animation.open_lid.playing
tag @s remove aj.mixer.animation.close_lid.playing
tag @s remove aj.mixer.animation.filled0.playing
tag @s remove aj.mixer.animation.filled1.playing
tag @s remove aj.mixer.animation.filled2.playing
tag @s remove aj.mixer.animation.filled3.playing
tag @s remove aj.mixer.animation.filled4.playing
tag @s remove aj.mixer.animation.filled5.playing