# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/animations/hide_badges/play'}
tag @s add aj.mixer.animation.hide_badges.playing
scoreboard players set @s aj.hide_badges.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:mixer/animations/hide_badges/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only