# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_vanilla_frosting.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_vanilla_frosting.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_vanilla_frosting.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_vanilla_frosting.node.4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_vanilla_frosting.node.5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ingredient_vanilla_frosting.node.6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_6 set from storage aj:uuid main.out