# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.forklift.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'forklift', 'function_path': 'animated_java:forklift/animations/pause_all'}
tag @s remove aj.forklift.animation.fork_height_0.playing
tag @s remove aj.forklift.animation.fork_height_1.playing
tag @s remove aj.forklift.animation.fork_height_2.playing
tag @s remove aj.forklift.animation.fork_height_3.playing
tag @s remove aj.forklift.animation.steer_reset.playing
tag @s remove aj.forklift.animation.steer_left.playing
tag @s remove aj.forklift.animation.steer_right.playing