# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mixer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mixer', 'function_path': 'animated_java:mixer/variants/pour_chocolate/apply'}
execute on passengers if entity @s[tag=aj.mixer.bone.flow] run function animated_java:mixer/variants/pour_chocolate/zzz/apply_to_bone_flow
return 1