# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ingredient_vanilla.root] run return 0
function #animated_java:ingredient_vanilla/as_root/pre_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:ingredient_vanilla/as_root/post_tick