# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
execute on passengers run function animated_java:launcher/animations/launch/zzz/frames/59_locator_commands/zzz/0