# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pan) {transformation: [-6.1667f,0f,0f,0f,0f,6.1667f,0f,1f,0f,0f,-6.1667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spring) {transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute on vehicle unless entity @s[tag=aj.transforms_only] as $(locator_layer0_lock_point) positioned ^0 ^1.0625 ^0 rotated ~0 ~0 run function animated_java:launcher/animations/launch/zzz/frames/60_locator_commands
data modify entity @s item.components."minecraft:custom_data" merge value {"cameras":{},"locators":{"layer0_lock_point":{"posx":0,"posy":1.0625,"posz":0,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:launcher/animations/launch/zzz/frames/60_root_commands