# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.empty.frame dummy
scoreboard objectives add aj.fill_batter.frame dummy
scoreboard objectives add aj.finish_baking.frame dummy
scoreboard objectives add aj.frost1.frame dummy
scoreboard objectives add aj.frost2.frame dummy
scoreboard objectives add aj.frost3.frame dummy