# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.text_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.text_display_text_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.text_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.text_display_text_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.layer1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_layer1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.frosting1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_frosting1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.order1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_order1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.layer2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_layer2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.frosting2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_frosting2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.order2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_order2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.layer3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_layer3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.frosting3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_frosting3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orders.node.order3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".uuids.bone_order3 set from storage aj:uuid main.out