# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.layer.node.layer] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_layer set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.layer.node.frosting] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s item.components."minecraft:custom_data".bones.bone_frosting set from storage aj:uuid main.out