# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.frosting_mixer.root] run return 0
function #animated_java:frosting_mixer/as_root/pre_tick
execute if entity @s[tag=aj.frosting_mixer.animation.fill0.playing] run function animated_java:frosting_mixer/animations/fill0/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.fill1.playing] run function animated_java:frosting_mixer/animations/fill1/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.fill2.playing] run function animated_java:frosting_mixer/animations/fill2/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.open.playing] run function animated_java:frosting_mixer/animations/open/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.start_mix.playing] run function animated_java:frosting_mixer/animations/start_mix/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.mix.playing] run function animated_java:frosting_mixer/animations/mix/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.end_mix.playing] run function animated_java:frosting_mixer/animations/end_mix/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.hide_ingredient_badges.playing] run function animated_java:frosting_mixer/animations/hide_ingredient_badges/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.show_ingredient_badges.playing] run function animated_java:frosting_mixer/animations/show_ingredient_badges/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.show_sugar_ingredient_check.playing] run function animated_java:frosting_mixer/animations/show_sugar_ingredient_check/zzz/on_tick
execute if entity @s[tag=aj.frosting_mixer.animation.show_flavor_ingredient_check.playing] run function animated_java:frosting_mixer/animations/show_flavor_ingredient_check/zzz/on_tick
execute on passengers if entity @s[tag=aj.frosting_mixer.data] run function animated_java:frosting_mixer/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~
function #animated_java:frosting_mixer/as_root/post_tick